Created BY: Sapia Cali <br>
Created Date: 11-24-2022 <br> 
Description: Step 1

In [1]:
from sqlalchemy import create_engine
import pandas as pd
import time
import datetime

In [2]:
%load_ext sql

In [3]:
engine = create_engine("mysql+pymysql://" + "root" + ":" + "" + "@" + "localhost" + ":" + "3306" + "/" + "dwh_finance" + "?" + "charset=utf8mb4")

In [4]:
%sql $engine.url

'Connected: root@dwh_finance'

In [5]:
#drop t_loan_level_data this cell is for Pia only
#loan_level_data_truncate = %sql DROP TABLE t_loan_level_data

In [6]:
pd.set_option('display.max_rows', 10000)
pd.set_option('display.max_columns', 10000)

### Import Data with Excel File
The excel file should be from the Loan Level Data category (2006 and 2007)

#### <font color='red'>Note: Enter the exact name of the excel file you want to insert into the table </font>

In [7]:
#excel_file = pd.read_csv('ExcelFile/ColExtCMLT06AMC10709.csv')
#df = pd.DataFrame(data=excel_file)
#df.sample()

,Loan Identification Number,Property Type Code,Occupancy Code,Loan Pupose Code,Note Type Code,Current Interest Rate,Pool Number,Original Loan Balance,Current Loan Balance,First Payment Date,Maturity Date,Current P&I Constant,Original Stated Term in Months,Foreclosure/Bankruptcy Code,LTV Ratio at Origination,State Code,Participation Code,Percentage Retained or Purchased,Interest Paid to Date,Amortization Type Code,"Institution, Branch, Investor or Servicer Code",Balloon Code,Last Appraisal Value,Negative Sign for Escrow Balance,Escrow Balance,Pledge Code,Lien Position,Payment Frequency Indicator,Delinquency History Flags,# of Times 30+ Delinq in Last 12 Months,Total Payment,# of Units,Interest Collection Code,Payment Type,Interest Only Expiration Date,Original Interest Rate,Index Code,Negative Sign for Margin,Margin,Next Interest Rate Change Date,Next Payment Change Date,Interest Rate Adjustment Period,Payment Adjustment Period,Periodic Rate Cap Percentage,Periodic Payment Cap,Lifetime Maximum Interest Rate Ceiling,Lifetime Rate Floor,Original P&I Constant,Original Index Value,Negative Amortization Limit %,Negative Amortization Code,First Rate Change Date,Interest Rate at Next Reset Date,Interest Rate Rounding Method,ARM Plan Code,ARM Convertibility Code,Mortgagor Last Name,Mortgagor First Name,Property Street Address,Property City,Property Zip Code,Property County Code,Underwriting Ratio 1,Underwriting Ratio 2,PMI Insurer Code,Origination Date,Other Data 1,Purchase Price of Property,Document Type Code,Buydown Type Code,Months to 1st Rate Change,Months to 1st Payment Change,ARM Look Back Period,Interest Rate Rounding Factor,Current LTV Ratio,Periodic Rate Floor Percentage,First Payment Change Date,Servicing Fee,Net WAC,Relocation Flag,Borrower Credit or Risk Grade,Other Data 2,Combined LTV,Other Data 3,Initial Periodic Rate Cap Pct,PMI Coverage Percentage,Section 32/HOEPA Flag,Senior Lien Amount,Current BPO LTV,Credit Score of Primary Borrower,BPO Value,BPO Date,Scheduled Balance,Scheduled Balance Paid Thru Date,Other Data 4,Product Code,Other Data 5,Prepay Penalty Flag,Prepay Penalty Term,Prepay Penalty Expiration Date,Prepay Penalty Code,Other Data 6
3763,146038401,2,1,3,2,7.99,2,454480.0,454480.0,406,336,3026.08,360,0,90.0,CA,NaN,0,80701.0,2,NaN,0,505000.0,NaN,NaN,NaN,1,1,NaN,0,NaN,100,2,4,NaN,7.99,10,NaN,5.5,NaN,NaN,6,6,1,0,13.99,7.99,3026.08,0,0,0,309.0,0,2,18,NaN,NaN,NaN,NaN,GREENFIELD,93927,53,0,0,NaN,20628,CMLT06AMC1,0.0,1,NaN,18.0,19.0,45,0.125,NaN,1,409.0,0.5,7.4737,NaN,NaN,NaN,90.0,NaN,2,NaN,NaN,NaN,0,647,0,NaN,454480.0,80701.0,NaN,18,NaN,Y,0,NaN,NaN,NaN

### Data Cleaning

In [8]:
#remove replace column name
df.columns = df.columns.str.replace(' ','_')  
df.columns = df.columns.str.replace('#','num')
df = df.rename(columns=str.lower)
df.sample()

,loan_identification_number,property_type_code,occupancy_code,loan_pupose_code,note_type_code,current_interest_rate,pool_number,original_loan_balance,current_loan_balance,first_payment_date,maturity_date,current_p&i_constant,original_stated_term_in_months,foreclosure/bankruptcy_code,ltv_ratio_at_origination,state_code,participation_code,percentage_retained_or_purchased,interest_paid_to_date,amortization_type_code,"institution,_branch,_investor_or_servicer_code",balloon_code,last_appraisal_value,negative_sign_for_escrow_balance,escrow_balance,pledge_code,lien_position,payment_frequency_indicator,delinquency_history_flags,num_of_times_30+_delinq_in_last_12_months,total_payment,num_of_units,interest_collection_code,payment_type,interest_only_expiration_date,original_interest_rate,index_code,negative_sign_for_margin,margin,next_interest_rate_change_date,next_payment_change_date,interest_rate_adjustment_period,payment_adjustment_period,periodic_rate_cap_percentage,periodic_payment_cap,lifetime_maximum_interest_rate_ceiling,lifetime_rate_floor,original_p&i_constant,original_index_value,negative_amortization_limit_%,negative_amortization_code,first_rate_change_date,interest_rate_at_next_reset_date,interest_rate_rounding_method,arm_plan_code,arm_convertibility_code,mortgagor_last_name,mortgagor_first_name,property_street_address,property_city,property_zip_code,property_county_code,underwriting_ratio_1,underwriting_ratio_2,pmi_insurer_code,origination_date,other_data_1,purchase_price_of_property,document_type_code,buydown_type_code,months_to_1st_rate_change,months_to_1st_payment_change,arm_look_back_period,interest_rate_rounding_factor,current_ltv_ratio,periodic_rate_floor_percentage,first_payment_change_date,servicing_fee,net_wac,relocation_flag,borrower_credit_or_risk_grade,other_data_2,combined_ltv,other_data_3,initial_periodic_rate_cap_pct,pmi_coverage_percentage,section_32/hoepa_flag,senior_lien_amount,current_bpo_ltv,credit_score_of_primary_borrower,bpo_value,bpo_date,scheduled_balance,scheduled_balance_paid_thru_date,other_data_4,product_code,other_data_5,prepay_penalty_flag,prepay_penalty_term,prepay_penalty_expiration_date,prepay_penalty_code,other_data_6
93,96962238,0,3,3,1,9.35,1,121500.0,120522.56,706,636,1008.37,360,0,90.0,NY,NaN,0,80701.0,1,NaN,0,135000.0,NaN,NaN,NaN,1,1,NaN,0,NaN,200,1,1,NaN,9.35,0,NaN,0.0,NaN,NaN,0,0,0,0,0.0,0.0,1008.37,0,0,0,NaN,0,0,9,NaN,NaN,NaN,NaN,WATERVLIET,12189,1,0,0,NaN,50625,CMLT06AMC1,0.0,3,NaN,NaN,NaN,0,0.0,NaN,0,NaN,0.5,8.8338,NaN,NaN,NaN,90.0,NaN,0,NaN,NaN,NaN,0,639,0,NaN,120522.56,80701.0,NaN,9,NaN,Y,0,NaN,NaN,NaN

In [9]:
# Add deal_id with CMLT06AMC1
df['deal_id'] = 'CMLT06AMC1'

#### <font color='red'>Note: Check the exact distribution date from the pdf of Certificate Holders Statement </font>

In [10]:
# Enter the distribution_date same with in the pdf File. Date format YYYY-MM-DD
df['distribution_date'] = '2007-09-25'

In [11]:
df.head()

,loan_identification_number,property_type_code,occupancy_code,loan_pupose_code,note_type_code,current_interest_rate,pool_number,original_loan_balance,current_loan_balance,first_payment_date,maturity_date,current_p&i_constant,original_stated_term_in_months,foreclosure/bankruptcy_code,ltv_ratio_at_origination,state_code,participation_code,percentage_retained_or_purchased,interest_paid_to_date,amortization_type_code,"institution,_branch,_investor_or_servicer_code",balloon_code,last_appraisal_value,negative_sign_for_escrow_balance,escrow_balance,pledge_code,lien_position,payment_frequency_indicator,delinquency_history_flags,num_of_times_30+_delinq_in_last_12_months,total_payment,num_of_units,interest_collection_code,payment_type,interest_only_expiration_date,original_interest_rate,index_code,negative_sign_for_margin,margin,next_interest_rate_change_date,next_payment_change_date,interest_rate_adjustment_period,payment_adjustment_period,periodic_rate_cap_percentage,periodic_payment_cap,lifetime_maximum_interest_rate_ceiling,lifetime_rate_floor,original_p&i_constant,original_index_value,negative_amortization_limit_%,negative_amortization_code,first_rate_change_date,interest_rate_at_next_reset_date,interest_rate_rounding_method,arm_plan_code,arm_convertibility_code,mortgagor_last_name,mortgagor_first_name,property_street_address,property_city,property_zip_code,property_county_code,underwriting_ratio_1,underwriting_ratio_2,pmi_insurer_code,origination_date,other_data_1,purchase_price_of_property,document_type_code,buydown_type_code,months_to_1st_rate_change,months_to_1st_payment_change,arm_look_back_period,interest_rate_rounding_factor,current_ltv_ratio,periodic_rate_floor_percentage,first_payment_change_date,servicing_fee,net_wac,relocation_flag,borrower_credit_or_risk_grade,other_data_2,combined_ltv,other_data_3,initial_periodic_rate_cap_pct,pmi_coverage_percentage,section_32/hoepa_flag,senior_lien_amount,current_bpo_ltv,credit_score_of_primary_borrower,bpo_value,bpo_date,scheduled_balance,scheduled_balance_paid_thru_date,other_data_4,product_code,other_data_5,prepay_penalty_flag,prepay_penalty_term,prepay_penalty_expiration_date,prepay_penalty_code,other_data_6,deal_id,distribution_date
0,97890198,0,1,1,2,8.900,2,261000.0,258699.27,706,636,2081.32,360,0,90.0,FL,NaN,0,80701.0,2,NaN,0,290000.0,NaN,NaN,NaN,1,1,NaN,0,NaN,200,1,1,NaN,8.900,10,NaN,6.0,NaN,NaN,6,6,1,0,14.900,8.900,2081.32,0,0,0,608.0,0,2,5,NaN,NaN,NaN,NaN,ORLANDO,32807,95,0,0,NaN,50622,CMLT06AMC1,320000.0,3,NaN,9.0,10.0,45,0.125,NaN,1,708.0,0.5,8.3837,NaN,NaN,NaN,90.0,NaN,2,NaN,NaN,NaN,0,649,0,NaN,258699.27,80701.0,NaN,5,NaN,Y,0,NaN,NaN,NaN,CMLT06AMC1,2007-09-25
1,98232192,0,3,1,2,8.425,1,150750.0,149390.55,806,736,1151.14,360,0,90.0,UT,NaN,0,80701.0,2,NaN,0,167500.0,NaN,NaN,NaN,1,1,NaN,0,NaN,200,1,1,NaN,8.425,10,NaN,6.0,NaN,NaN,6,6,1,0,14.425,8.425,1151.14,0,0,0,708.0,0,2,5,NaN,NaN,NaN,NaN,OREM,84058,49,0,0,NaN,60612,CMLT06AMC1,167500.0,1,NaN,10.0,11.0,45,0.125,NaN,1,808.0,0.5,7.9088,NaN,NaN,NaN,90.0,NaN,2,NaN,NaN,NaN,0,816,0,NaN,149390.55,80701.0,NaN,5,NaN,Y,0,NaN,NaN,NaN,CMLT06AMC1,2007-09-25
2,149634024,0,1,3,1,9.750,1,87000.0,85909.16,706,636,747.47,360,0,69.6,PA,NaN,0,80701.0,1,NaN,0,125000.0,NaN,NaN,NaN,1,1,NaN,0,NaN,100,1,1,NaN,9.750,0,NaN,0.0,NaN,NaN,0,0,0,0,0.000,0.000,747.47,0,0,0,NaN,0,0,9,NaN,NaN,NaN,NaN,PHILADELPHI,19145,101,0,0,NaN,50618,CMLT06AMC1,0.0,1,NaN,NaN,NaN,0,0.000,NaN,0,NaN,0.5,9.2338,NaN,NaN,NaN,69.6,NaN,0,NaN,NaN,NaN,0,530,0,NaN,85909.16,80701.0,NaN,9,NaN,Y,0,NaN,NaN,NaN,CMLT06AMC1,2007-09-25
3,97026637,0,3,1,2,9.850,1,78400.0,77830.73,706,636,679.35,360,0,80.0,IA,NaN,0,60701.0,2,NaN,0,98000.0,NaN,NaN,NaN,1,1,NaN,0,NaN,400,1,1,NaN,9.850,10,NaN,6.0,NaN,NaN,6,6,1,0,15.850,9.850,679.35,0,0,0,608.0,0,2,5,NaN,NaN,NaN,NaN,DES MOINES,50313,153,0,0,NaN,50612,CMLT06AMC1,98000.0,1,NaN,9.0,10.0,45,0.125,NaN,1,708.0,0.5,9.3338,NaN,NaN,NaN,80.0,NaN,2,NaN,NaN,NaN,0,657,0,NaN,77830.73,60701.0,NaN,5,NaN,N,0,NaN,NaN,NaN,CMLT06AMC1,2007-09-25
4,97559074,0,3,3,2,9.600,1,148500.0,147364.98,706,636,1259.52,360,0,90.0,PA,NaN,0,80701.0,2,NaN,0,165000.0,NaN,NaN,NaN,1,1,NaN,0,NaN,200,1,1,NaN,9.600,10,NaN,6.0,NaN,NaN,6,6,1,0,15.600,9.600,1259.52,0,0,0,608.0,0,2,5,NaN,NaN,NaN,NaN,PHILADELPHI,19150,101,0,0,NaN,50631,CMLT06AMC1,0.0,3,NaN,9.0,10.0,45,0.125,NaN,1,708.0,0.5,9.0838,NaN,NaN,NaN,90.0,NaN,2,NaN,NaN,NaN,0,640,0,NaN,147364.98,80701.0,NaN,5,NaN,Y,0,NaN,NaN,NaN,CMLT06AMC1,2007-09-25

In [12]:
# Delete duplicate rows 
df = df.drop_duplicates()

In [13]:
df.shape

(5117, 104)

In [14]:
df.sample()

,loan_identification_number,property_type_code,occupancy_code,loan_pupose_code,note_type_code,current_interest_rate,pool_number,original_loan_balance,current_loan_balance,first_payment_date,maturity_date,current_p&i_constant,original_stated_term_in_months,foreclosure/bankruptcy_code,ltv_ratio_at_origination,state_code,participation_code,percentage_retained_or_purchased,interest_paid_to_date,amortization_type_code,"institution,_branch,_investor_or_servicer_code",balloon_code,last_appraisal_value,negative_sign_for_escrow_balance,escrow_balance,pledge_code,lien_position,payment_frequency_indicator,delinquency_history_flags,num_of_times_30+_delinq_in_last_12_months,total_payment,num_of_units,interest_collection_code,payment_type,interest_only_expiration_date,original_interest_rate,index_code,negative_sign_for_margin,margin,next_interest_rate_change_date,next_payment_change_date,interest_rate_adjustment_period,payment_adjustment_period,periodic_rate_cap_percentage,periodic_payment_cap,lifetime_maximum_interest_rate_ceiling,lifetime_rate_floor,original_p&i_constant,original_index_value,negative_amortization_limit_%,negative_amortization_code,first_rate_change_date,interest_rate_at_next_reset_date,interest_rate_rounding_method,arm_plan_code,arm_convertibility_code,mortgagor_last_name,mortgagor_first_name,property_street_address,property_city,property_zip_code,property_county_code,underwriting_ratio_1,underwriting_ratio_2,pmi_insurer_code,origination_date,other_data_1,purchase_price_of_property,document_type_code,buydown_type_code,months_to_1st_rate_change,months_to_1st_payment_change,arm_look_back_period,interest_rate_rounding_factor,current_ltv_ratio,periodic_rate_floor_percentage,first_payment_change_date,servicing_fee,net_wac,relocation_flag,borrower_credit_or_risk_grade,other_data_2,combined_ltv,other_data_3,initial_periodic_rate_cap_pct,pmi_coverage_percentage,section_32/hoepa_flag,senior_lien_amount,current_bpo_ltv,credit_score_of_primary_borrower,bpo_value,bpo_date,scheduled_balance,scheduled_balance_paid_thru_date,other_data_4,product_code,other_data_5,prepay_penalty_flag,prepay_penalty_term,prepay_penalty_expiration_date,prepay_penalty_code,other_data_6,deal_id,distribution_date
1375,97245195,2,1,1,2,8.45,2,404000.0,404000.0,706,636,2844.84,360,0,80.0,FL,NaN,0,80701.0,2,NaN,0,505000.0,NaN,NaN,NaN,1,1,NaN,0,NaN,100,2,4,NaN,8.45,10,NaN,6.0,NaN,NaN,6,6,1,0,14.45,8.45,2844.84,0,0,0,608.0,0,2,17,NaN,NaN,NaN,NaN,NORTH PORT,34286,115,0,0,NaN,50631,CMLT06AMC1,510000.0,1,NaN,9.0,10.0,45,0.125,NaN,1,708.0,0.5,7.9337,NaN,NaN,NaN,80.0,NaN,2,NaN,NaN,NaN,0,637,0,NaN,404000.0,80701.0,NaN,17,NaN,Y,0,NaN,NaN,NaN,CMLT06AMC1,2007-09-25

In [15]:
current_date = datetime.datetime.now()
date_today = str(current_date.year)+('-')+str(current_date.month)+('-')+str(current_date.day)
# Input date today
df['import_date'] = date_today

In [16]:
#df.to_sql(con=engine,name='t_loan_level_data',if_exists='append',index=False)

5117

In [17]:
loan_level_data1 = %sql SELECT * FROM t_loan_level_data
loan_level_data1 = pd.DataFrame(data=loan_level_data1)
loan_level_data1.head()

 * mysql+pymysql://root:***@localhost:3306/dwh_finance?charset=utf8mb4
64016 rows affected.

,loan_identification_number,property_type_code,occupancy_code,loan_pupose_code,note_type_code,current_interest_rate,pool_number,original_loan_balance,current_loan_balance,first_payment_date,maturity_date,current_p&i_constant,original_stated_term_in_months,foreclosure/bankruptcy_code,ltv_ratio_at_origination,state_code,participation_code,percentage_retained_or_purchased,interest_paid_to_date,amortization_type_code,"institution,_branch,_investor_or_servicer_code",balloon_code,last_appraisal_value,negative_sign_for_escrow_balance,escrow_balance,pledge_code,lien_position,payment_frequency_indicator,delinquency_history_flags,num_of_times_30+_delinq_in_last_12_months,total_payment,num_of_units,interest_collection_code,payment_type,interest_only_expiration_date,original_interest_rate,index_code,negative_sign_for_margin,margin,next_interest_rate_change_date,next_payment_change_date,interest_rate_adjustment_period,payment_adjustment_period,periodic_rate_cap_percentage,periodic_payment_cap,lifetime_maximum_interest_rate_ceiling,lifetime_rate_floor,original_p&i_constant,original_index_value,negative_amortization_limit_%,negative_amortization_code,first_rate_change_date,interest_rate_at_next_reset_date,interest_rate_rounding_method,arm_plan_code,arm_convertibility_code,mortgagor_last_name,mortgagor_first_name,property_street_address,property_city,property_zip_code,property_county_code,underwriting_ratio_1,underwriting_ratio_2,pmi_insurer_code,origination_date,other_data_1,purchase_price_of_property,document_type_code,buydown_type_code,months_to_1st_rate_change,months_to_1st_payment_change,arm_look_back_period,interest_rate_rounding_factor,current_ltv_ratio,periodic_rate_floor_percentage,first_payment_change_date,servicing_fee,net_wac,relocation_flag,borrower_credit_or_risk_grade,other_data_2,combined_ltv,other_data_3,initial_periodic_rate_cap_pct,pmi_coverage_percentage,section_32/hoepa_flag,senior_lien_amount,current_bpo_ltv,credit_score_of_primary_borrower,bpo_value,bpo_date,scheduled_balance,scheduled_balance_paid_thru_date,other_data_4,product_code,other_data_5,prepay_penalty_flag,prepay_penalty_term,prepay_penalty_expiration_date,prepay_penalty_code,other_data_6,deal_id,distribution_date,import_date
0,149572588,0,1,3,2,9.20,1,260000.0,259448.84,706,636,2129.55,360,0,80.00,NY,None,0,90601.0,2,None,0,325000.0,None,None,None,1,1,None,0.0,None,200,1,1,None,9.20,10,None,6.25,None,None,6,6,1,0,15.20,9.20,2129.55,0,0,0,608.0,0,2,5,None,None,None,None,MILLBROOK,12545,27,0,0,None,50603,NaN,0.0,0,None,20.0,21.0,45,0.125,None,1,708.0,0.5,8.685,None,None,None,80.00,None,2,None,None,None,0,561,0,None,259448.84,90601.0,None,5,None,N,0,None,None,None,CMLT06AMC1,2006-10-25,2022-11-23
1,98016793,0,1,3,2,6.85,1,482000.0,482000.00,706,636,2751.42,360,0,79.67,CA,None,0,100601.0,2,None,0,605000.0,None,None,None,1,1,None,0.0,None,200,2,4,None,6.85,10,None,6.00,None,None,6,6,1,0,12.85,6.85,2751.42,0,0,0,608.0,0,2,17,None,None,None,None,LOS ANGELES,90022,37,0,0,None,50624,NaN,0.0,0,None,20.0,21.0,45,0.125,None,1,708.0,0.5,6.335,None,None,None,79.67,None,2,None,None,None,0,705,0,None,482000.00,100601.0,None,17,None,Y,0,None,None,None,CMLT06AMC1,2006-10-25,2022-11-23
2,96862230,0,1,3,1,9.90,1,130000.0,129762.08,706,636,1131.25,360,0,100.00,WI,None,0,100601.0,1,None,0,130000.0,None,None,None,1,1,None,0.0,None,200,1,1,None,9.90,0,None,0.00,None,None,0,0,0,0,0.00,0.00,1131.25,0,0,0,NaN,0,0,9,None,None,None,None,MILWAUKEE,53210,79,0,0,None,50623,NaN,0.0,0,None,NaN,NaN,0,0.000,None,0,NaN,0.5,9.385,None,None,None,100.00,None,0,None,None,None,0,639,0,None,129762.08,100601.0,None,9,None,N,0,None,None,None,CMLT06AMC1,2006-10-25,2022-11-23
3,98819030,0,1,3,2,7.95,1,503500.0,503499.86,806,736,3335.69,360,0,93.24,CA,None,0,100601.0,2,None,0,540000.0,None,None,None,1,1,None,0.0,None,200,2,4,None,7.95,10,None,6.00,None,None,6,6,1,0,13.95,7.95,3335.69,0,0,0,708.0,0,2,17,None,None,None,None,LOS ANGELES,90043,37,0,0,None,60622,NaN,0.0,0,None,21.0,22.0,45,0.125,None,1,808.0,0.5,7.435,None,None,None,93.24,None,2,None,None,None,0,630,0,None,503499.86,100601.0,None,17,None,Y,0,None,None,None,CMLT06AMC1,2006-10-25,2022-11-23
4,95577391,0,1,1,2,6.99,2,426968.0,425552.97,706,636,2837.77,360,0,95.00,NY,None,0,100601.0,2,None,0,449440.0,None,None,None,1,1,None,0.0,None,200,1,1,None,6.99,10,None,6.00,None,None,6,6,1,0,12.99,6.99,2837.77,0,0,0,609.0,0,2,8,None,None,None,None,BROOKLYN,11236,47,0,0,None,50604,NaN,449440.0,0,None,32.0,33.0,45,0.125,None,1,709.0,0.5,6.475,None,None,None,95.00,None,2,None,None,None,0,642,0,None,425552.97,100601.0,None,8,None,N,0,None,None,None,CMLT06AMC1,2006-10-25,2022-11-23

In [18]:
loan_level_data1 = loan_level_data1.drop_duplicates()

In [19]:
loan_level_data_count = loan_level_data1.groupby(['deal_id','distribution_date'])['distribution_date'].count().reset_index(name = 'loan_level_data_count')
loan_level_data_count

       deal_id distribution_date  loan_level_data_count
0   CMLT06AMC1        2006-10-25                   6522
1   CMLT06AMC1        2006-11-27                   6423
2   CMLT06AMC1        2006-12-26                   6234
3   CMLT06AMC1        2007-01-25                   6121
4   CMLT06AMC1        2007-02-26                   5839
5   CMLT06AMC1        2007-03-26                   5713
6   CMLT06AMC1        2007-04-25                   5605
7   CMLT06AMC1        2007-05-25                   5509
8   CMLT06AMC1        2007-06-25                   5417
9   CMLT06AMC1        2007-07-25                   5332
10  CMLT06AMC1        2007-08-27                    184
11  CMLT06AMC1        2007-09-25                   5117